### ISSUE TITLE
Choosing A License

### ISSUE THREAD

**Issue by rahul286** [wpveda/book#6]
I am clueless as usual when it comes to licensing.

I think @yapapaya  and @bombaypirate can better solve this. :-)

**Comment by actual-saurabh** [comment]
Try one of these: https://creativecommons.org/licenses/

For absolute permissions you could use [CC0 license](http://creativecommons.org/about/cc0) with the [public domain mark](http://creativecommons.org/about/pdm). I personally prefer the CC0.

**Comment by bombaypirate** [comment]
Yeah. Mostly the license under consideration is Creative Commons https://creativecommons.org/licenses/

@yapapaya I am confused between using [CC0](https://creativecommons.org/publicdomain/zero/1.0/) and [CC-NC](http://creativecommons.org/licenses/by-nc/2.0/) - any reason you like CC0 more than other Creative Commons licence?

Why NC?

Mainly, I am concerned that somewhere down the line in the future - CC-0 licence might allow someone to just put a wrapper around this book and start monetizing it. Since this will have more than one or two contributors it can cause some major issues to people who are contributing.

That said, those problems are very very far away down the line.

Though I am unable to find what WordPress Codex or Developer Handbook is using.

**Comment by rahul286** [comment]
How does this sound - http://en.wikipedia.org/wiki/GNU_Free_Documentation_License  ?

**Comment by mbtamuli** [comment]
https://choosealicense.com/

Very simple and easy to use explanations.

**Comment by rahul286** [comment]
@mbtamuli Thanks. Picked MIT for now.
